language: r
cache: packages
pandoc_version: 2.2.1

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

notifications:
  slack:
    rooms: mW3I0g2NVINDRm0FllfekcHT

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: master
  local_dir: _book
  on:
    branch: devel
