# Créer et Éditer des graphiques avec R


R dispose de nombreux outils pour faire un travail approfondi de visualisation des données. Lorsque R est installé, nous avons à notre disposition de multiple fonctionnalités pour éditer nos figures et les exporter sous différents formats. L'édition de graphique sous R peut être divisé en deux branches : d'un côté l'approche développé dans le package _graphics_ et de l'autre l'approche encore plus flexible développé dans le package _grid_.


## Le système graphique du package _graphics_

Le package _graphics_ est une implémentation du système graphique historique de _S_. Il s'agit, en effet, de la ré-écriture des fonctionnalités de la bibliothèque GRZ pour les utiliser avec R. Ce travail a été en large partie mené par Ross Ihaka, l'un des deux initiateurs de R. Avec ce package, nous pouvons obtenir en très peu de lignes de commandes des graphiques tout à fait convenable (grâce, par exemple, à la fonction _plot()_). Nous pouvons également travailler par couches succéssives pour ajouter un à un les éléments du graphiques et obtenir un rendu graphique plus aboutit. l'utilisation de _graphics_ est répandue, simple, intuitive et sa puissance est souvent mésestimée. C'est pour ces raisons que nous avons choisi de la détailler dans ce livre. De manière générale, pour faire un graphique avec ce système on procède en trois étapes\&nbsp:

1. On définit les paramètre graphiques globaux (fonction _par()_ voir chapitre)
2. On trace le plot ajoute la fonction que nous souhaitons (_plot()_, _boxplot()_,....)
3. On ajoute les différents éléments supplémentaire : points, lignes, textes, légendes.

Dans la suite, nous reprennons point par point ces différentes étapes. Une des principales faiblesses de ce système réside dans la difficulté à changer les éléments déjà placés. La plupart du temps, il est nécessaire de ré-exécuter tout le code modifier. Ce système est riche en fonctionnalités et plusieurs package de R utilise ce sytème pour implémenter des graphiques plus spécifiques.
Le package _plotrix_, dévellopé par Jim Lemon, utilise _graphics_ et ajoute à celui-ci de mombreux types de graphiques supplémentaires dont les graphiques en co-ordonnées polaires.



## Le système graphique du package _grid_

Le package _grid_, que nous devons à Paul Murrel, est un système graphique puissant qui donne un cardre performant pour développer des graphiques précis. Il y a plusieurs éléments importants sur lesquels nous revonnons en annexe. Le premier est le concept de _viewPort_ : il s'agit de zone rectangulaire qui sont définis dans l'espace et avec un système de co-ordonnées. Il est possible d'en utiliser autant que sohaiter, elles peuvent se recouper ou non et posséder des paramètres. C'est en quelques sortes un ensmble très flexibles de calques. Il est possible de naviquer à travers pour placer à tout moment n'importe quel élément du futurr gatpqhique. Le package _grid_  définis ces propres fonction primitive pour déssiner points lignes et polygones. En plus d'un affichage et contrairement à ce que nous avons dans le apckage _graphics_, dans _grid_, les objets affichés sont aussi des objets que l'on peut modifier à sa guise. Cela donne au package _grid_ une grane puissance. Il serait bien long de redévolppé chauqe graphique avec grid et comparer _graphics_ et _grid_ est un peu bancal en se sens qu'il ne sont pas réellement implmmenté et qu'il faut les faire à la main. Néanmoins c'est grâce à sa puissce que sont nés deux autres systèmes de graphique à succès. Le premier est le système développé par Deepayan Sarkar dans le package _lattice_. Le second est une implémentation de la grammaire des graphiques, _ggplot2_ que nous devons à Hadley Wickham. Notez que depuis peu, _grid_ et _graphics_ ont été reliés partiellement grâce au package _gridGraphics_ qui permet d'écrire les fonctions graphics en _grid_.
Ces packages doivent beaucoup au travail de Paul Murrel dont le livre _R graphics_ [ref] et aussi un chapitre sur lattice demeure une référence pour approfondir l'édition de graphiques avec R.

Lorsque les graohiques sont produits que ce soit avec _grid_ ou _graphics_, pour les exporter dans différent fornat, on fait appelà un troisième package : _grDevices_.


## Les graphiques interactives

Les graohiques qui font appel à des bibliothèques JS.
